before_install:
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/terry_guo-gcc-arm-embedded-precise.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
install:
    - sudo apt-get install gcc-arm-none-eabi
before_script:
    - cp examples/test-session.cpp main.cpp
script:
    - make
env:
  matrix:
    - BOARD=maple_mini
    - BOARD=maple_native
    - BOARD=st_stm3220g_eval
